-- =====================================================
-- SEED DATA MIGRATION FOR SOLAR SHOP
-- File: 002_seed_data.sql
-- Description: Comprehensive seed data for all tables
-- =====================================================

-- Insert Categories
INSERT INTO categories (id, name, slug, description, parent_id, image_url, is_active, sort_order, created_at, updated_at) VALUES
('cat_solar_panels', 'Solar Panels', 'solar-panels', 'High-efficiency solar panels for residential and commercial use', NULL, 'https://images.unsplash.com/photo-1509391366360-2e959784a276?w=500&h=500&fit=crop', true, 1, NOW(), NOW()),
('cat_inverters', 'Inverters', 'inverters', 'Solar inverters to convert DC to AC power', NULL, 'https://images.unsplash.com/photo-1497435334941-8c899ee9e8e9?w=500&h=500&fit=crop', true, 2, NOW(), NOW()),
('cat_batteries', 'Battery Storage', 'battery-storage', 'Energy storage solutions for solar systems', NULL, 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=500&h=500&fit=crop', true, 3, NOW(), NOW()),
('cat_mounting', 'Mounting Systems', 'mounting-systems', 'Roof and ground mounting solutions', NULL, 'https://images.unsplash.com/photo-1581092160562-40aa08e78837?w=500&h=500&fit=crop', true, 4, NOW(), NOW()),
('cat_monitoring', 'Monitoring Systems', 'monitoring-systems', 'Solar system monitoring and optimization', NULL, 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=500&h=500&fit=crop', true, 5, NOW(), NOW()),
('cat_accessories', 'Accessories', 'accessories', 'Cables, connectors, and other solar accessories', NULL, 'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=500&h=500&fit=crop', true, 6, NOW(), NOW()),

-- Subcategories for Solar Panels
('cat_mono_panels', 'Monocrystalline Panels', 'monocrystalline-panels', 'High-efficiency monocrystalline solar panels', 'cat_solar_panels', 'https://images.unsplash.com/photo-1509391366360-2e959784a276?w=500&h=500&fit=crop', true, 1, NOW(), NOW()),
('cat_poly_panels', 'Polycrystalline Panels', 'polycrystalline-panels', 'Cost-effective polycrystalline solar panels', 'cat_solar_panels', 'https://images.unsplash.com/photo-1509391366360-2e959784a276?w=500&h=500&fit=crop', true, 2, NOW(), NOW()),
('cat_bifacial_panels', 'Bifacial Panels', 'bifacial-panels', 'Double-sided solar panels for maximum efficiency', 'cat_solar_panels', 'https://images.unsplash.com/photo-1509391366360-2e959784a276?w=500&h=500&fit=crop', true, 3, NOW(), NOW()),

-- Subcategories for Inverters
('cat_string_inverters', 'String Inverters', 'string-inverters', 'Traditional string inverters for solar systems', 'cat_inverters', 'https://images.unsplash.com/photo-1497435334941-8c899ee9e8e9?w=500&h=500&fit=crop', true, 1, NOW(), NOW()),
('cat_micro_inverters', 'Micro Inverters', 'micro-inverters', 'Panel-level micro inverters for optimal performance', 'cat_inverters', 'https://images.unsplash.com/photo-1497435334941-8c899ee9e8e9?w=500&h=500&fit=crop', true, 2, NOW(), NOW()),
('cat_power_optimizers', 'Power Optimizers', 'power-optimizers', 'DC power optimizers for enhanced system performance', 'cat_inverters', 'https://images.unsplash.com/photo-1497435334941-8c899ee9e8e9?w=500&h=500&fit=crop', true, 3, NOW(), NOW());

-- Insert Products
INSERT INTO products (id, name, slug, description, short_description, sku, price, original_price, category_id, brand, model, specifications, features, certifications, warranty_years, weight, dimensions, images, in_stock, stock_quantity, stock_status, is_featured, is_active, rating_average, rating_count, free_shipping, created_at, updated_at) VALUES

-- Solar Panels
('prod_panel_mono_400w', 'SolarMax Pro 400W Monocrystalline Panel', 'solarmax-pro-400w-mono', 'High-efficiency 400W monocrystalline solar panel with excellent performance in low-light conditions. Features advanced PERC cell technology and robust aluminum frame for long-lasting durability.', 'High-efficiency 400W monocrystalline solar panel', 'SM-MONO-400W-001', 299.99, 349.99, 'cat_mono_panels', 'SolarMax', 'SM-400M-PERC', '{"power_output": "400W", "efficiency": "21.2%", "voltage_max": "40.5V", "current_max": "9.88A", "cell_type": "Monocrystalline PERC", "cells": "72 cells", "temperature_coefficient": "-0.38%/°C"}', '["PERC cell technology", "Anti-reflective coating", "Corrosion-resistant frame", "IP67 junction box", "25-year performance warranty"]', '["IEC 61215", "IEC 61730", "CE", "TUV", "UL 1703"]', 25, 22.5, '{"length": 2000, "width": 1000, "height": 35, "unit": "mm"}', '[{"url": "https://images.unsplash.com/photo-1509391366360-2e959784a276?w=800&h=600&fit=crop", "alt": "SolarMax Pro 400W Panel", "is_primary": true}]', true, 150, 'in_stock', true, true, 4.7, 89, true, NOW(), NOW()),

('prod_panel_poly_320w', 'EcoSolar 320W Polycrystalline Panel', 'ecosolar-320w-poly', 'Reliable and cost-effective 320W polycrystalline solar panel perfect for residential installations. Excellent value for money with proven performance.', 'Cost-effective 320W polycrystalline solar panel', 'ES-POLY-320W-002', 199.99, 249.99, 'cat_poly_panels', 'EcoSolar', 'ES-320P-STD', '{"power_output": "320W", "efficiency": "19.5%", "voltage_max": "37.2V", "current_max": "8.61A", "cell_type": "Polycrystalline", "cells": "72 cells", "temperature_coefficient": "-0.41%/°C"}', '["Multi-crystalline silicon cells", "Anodized aluminum frame", "Tempered glass", "Standard warranty", "Proven technology"]', '["IEC 61215", "IEC 61730", "CE", "TUV"]', 20, 21.8, '{"length": 1956, "width": 992, "height": 40, "unit": "mm"}', '[{"url": "https://images.unsplash.com/photo-1509391366360-2e959784a276?w=800&h=600&fit=crop", "alt": "EcoSolar 320W Panel", "is_primary": true}]', true, 200, 'in_stock', false, true, 4.3, 156, true, NOW(), NOW()),

('prod_panel_bifacial_450w', 'PowerTech Bifacial 450W Panel', 'powertech-bifacial-450w', 'Advanced bifacial solar panel that generates power from both sides, increasing energy yield by up to 30%. Perfect for ground-mount and elevated installations.', 'High-performance bifacial 450W solar panel', 'PT-BIFACIAL-450W-003', 399.99, 449.99, 'cat_bifacial_panels', 'PowerTech', 'PT-450BF-PERC', '{"power_output": "450W", "efficiency": "22.1%", "voltage_max": "41.8V", "current_max": "10.77A", "cell_type": "Bifacial PERC", "cells": "72 cells", "bifaciality": "85%", "temperature_coefficient": "-0.35%/°C"}', '["Bifacial design", "Transparent backsheet", "Enhanced durability", "Higher energy yield", "Premium glass-glass construction"]', '["IEC 61215", "IEC 61730", "CE", "TUV", "UL 1703", "IEC 61701"]', 30, 24.2, '{"length": 2094, "width": 1038, "height": 35, "unit": "mm"}', '[{"url": "https://images.unsplash.com/photo-1509391366360-2e959784a276?w=800&h=600&fit=crop", "alt": "PowerTech Bifacial 450W Panel", "is_primary": true}]', true, 75, 'in_stock', true, true, 4.8, 42, true, NOW(), NOW()),

-- Inverters
('prod_inv_string_5kw', 'SolarInvert String 5kW Inverter', 'solarinvert-string-5kw', 'Reliable 5kW string inverter with advanced MPPT technology and comprehensive monitoring capabilities. Perfect for residential solar installations.', 'High-efficiency 5kW string inverter', 'SI-STRING-5KW-001', 899.99, 999.99, 'cat_string_inverters', 'SolarInvert', 'SI-5000TL', '{"power_output": "5000W", "efficiency": "97.6%", "mppt_trackers": 2, "max_dc_voltage": "1000V", "ac_voltage": "230V", "frequency": "50Hz", "protection_rating": "IP65"}', '["Dual MPPT trackers", "WiFi monitoring", "Fanless design", "Compact size", "Easy installation"]', '["IEC 62109", "EN 50438", "VDE-AR-N 4105", "CE", "G83/2"]', 10, 18.5, '{"length": 470, "width": 350, "height": 180, "unit": "mm"}', '[{"url": "https://images.unsplash.com/photo-1497435334941-8c899ee9e8e9?w=800&h=600&fit=crop", "alt": "SolarInvert String 5kW Inverter", "is_primary": true}]', true, 85, 'in_stock', true, true, 4.6, 73, false, NOW(), NOW()),

('prod_inv_micro_300w', 'MicroMax 300W Micro Inverter', 'micromax-300w-micro', 'Panel-level micro inverter providing maximum energy harvest and individual panel monitoring. Ideal for complex roof layouts and shading conditions.', 'High-performance 300W micro inverter', 'MM-MICRO-300W-002', 149.99, 179.99, 'cat_micro_inverters', 'MicroMax', 'MM-300M-PERC', '{"power_output": "300W", "efficiency": "96.5%", "max_dc_voltage": "60V", "ac_voltage": "230V", "frequency": "50Hz", "protection_rating": "IP67"}', '["Panel-level optimization", "Rapid shutdown", "25-year warranty", "Easy installation", "Real-time monitoring"]', '["IEC 62109", "EN 50438", "UL 1741", "CE", "FCC"]', 25, 0.7, '{"length": 166, "width": 175, "height": 33, "unit": "mm"}', '[{"url": "https://images.unsplash.com/photo-1497435334941-8c899ee9e8e9?w=800&h=600&fit=crop", "alt": "MicroMax 300W Micro Inverter", "is_primary": true}]', true, 300, 'in_stock', false, true, 4.5, 128, false, NOW(), NOW()),

-- Battery Storage
('prod_battery_10kwh', 'EnergyStore 10kWh Lithium Battery', 'energystore-10kwh-lithium', 'High-capacity 10kWh lithium battery system with integrated BMS and smart monitoring. Perfect for residential energy storage and backup power.', 'Advanced 10kWh lithium battery storage system', 'ES-BATT-10KWH-001', 4999.99, 5499.99, 'cat_batteries', 'EnergyStore', 'ES-10K-LiFePO4', '{"capacity": "10kWh", "voltage": "48V", "chemistry": "LiFePO4", "cycles": "6000+", "efficiency": "95%", "max_discharge": "5kW", "operating_temp": "-10°C to 50°C"}', '["LiFePO4 chemistry", "Integrated BMS", "Modular design", "Smart monitoring", "15-year warranty"]', '["IEC 62619", "UN38.3", "CE", "UL 1973", "IEC 61000"]', 15, 85, '{"length": 600, "width": 400, "height": 200, "unit": "mm"}', '[{"url": "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=600&fit=crop", "alt": "EnergyStore 10kWh Battery", "is_primary": true}]', true, 45, 'in_stock', true, true, 4.7, 34, false, NOW(), NOW()),

-- Mounting Systems
('prod_mount_roof_kit', 'RoofMount Pro Tile Mounting Kit', 'roofmount-pro-tile-kit', 'Professional roof mounting system for tile roofs. Includes all necessary components for secure and weatherproof installation.', 'Complete tile roof mounting kit for 10 panels', 'RM-TILE-KIT-001', 299.99, 349.99, 'cat_mounting', 'RoofMount', 'RM-TILE-10P', '{"panel_capacity": "10 panels", "roof_type": "Tile", "material": "Aluminum/Stainless Steel", "wind_load": "2400 Pa", "snow_load": "5400 Pa"}', '["Corrosion resistant", "Easy installation", "Adjustable tilt", "Weatherproof sealing", "25-year warranty"]', '["TUV certified", "CE", "ISO 9001", "Wind load tested"]', 25, 35, '{"length": 1200, "width": 800, "height": 150, "unit": "mm"}', '[{"url": "https://images.unsplash.com/photo-1581092160562-40aa08e78837?w=800&h=600&fit=crop", "alt": "RoofMount Pro Tile Kit", "is_primary": true}]', true, 120, 'in_stock', false, true, 4.4, 67, false, NOW(), NOW()),

-- Monitoring Systems
('prod_monitor_gateway', 'SolarWatch Monitoring Gateway', 'solarwatch-monitoring-gateway', 'Advanced monitoring gateway for comprehensive solar system monitoring. Real-time data, alerts, and performance analytics.', 'Professional solar monitoring gateway', 'SW-GATEWAY-001', 199.99, 249.99, 'cat_monitoring', 'SolarWatch', 'SW-GW-PRO', '{"connectivity": "WiFi/Ethernet/4G", "data_logging": "20 years", "update_interval": "5 minutes", "max_inverters": "50", "api_access": "Yes"}', '["Real-time monitoring", "Mobile app", "Email alerts", "Performance analytics", "Weather data integration"]', '["CE", "FCC", "IC", "RCM"]', 5, 0.8, '{"length": 120, "width": 80, "height": 25, "unit": "mm"}', '[{"url": "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&h=600&fit=crop", "alt": "SolarWatch Gateway", "is_primary": true}]', true, 200, 'in_stock', false, true, 4.3, 91, false, NOW(), NOW()),

-- Accessories
('prod_cable_dc_50m', 'SolarCable DC 4mm² 50m Red/Black', 'solarcable-dc-4mm-50m', 'High-quality DC cable specifically designed for solar installations. UV-resistant and suitable for outdoor use.', 'Professional DC solar cable 4mm² 50m', 'SC-DC-4MM-50M-001', 89.99, 109.99, 'cat_accessories', 'SolarCable', 'SC-DC-4-50', '{"cross_section": "4mm²", "length": "50m", "voltage_rating": "1500V DC", "temperature_range": "-40°C to +90°C", "insulation": "XLPE"}', '["UV resistant", "Halogen free", "TUV certified", "Double insulation", "25-year lifespan"]', '["TUV 2 PfG 1169", "IEC 62930", "EN 50618", "UL 4703"]', 25, 12, '{"diameter": "6.4mm", "bend_radius": "32mm", "unit": "mm"}', '[{"url": "https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=800&h=600&fit=crop", "alt": "SolarCable DC Cable", "is_primary": true}]', true, 80, 'in_stock', false, true, 4.6, 45, false, NOW(), NOW());

-- Insert Offers/Coupons
INSERT INTO offers (id, code, title, description, discount_type, discount_value, max_discount_amount, min_order_amount, max_order_amount, applicable_product_ids, excluded_product_ids, max_usage, current_usage, max_usage_per_customer, start_date, end_date, is_active, auto_apply, featured, created_at, updated_at) VALUES

('offer_welcome10', 'WELCOME10', 'Welcome 10% Off', 'Get 10% off your first order! Perfect for new customers starting their solar journey.', 'percentage', 10, 500, 100, NULL, NULL, NULL, 1000, 45, 1, NOW() - INTERVAL '7 days', NOW() + INTERVAL '30 days', true, false, true, NOW(), NOW()),

('offer_solar_bundle', 'SOLARBUNDLE', 'Solar Panel Bundle Deal', 'Save €200 on solar panel purchases over €2000. Perfect for complete system installations.', 'fixed_amount', 200, NULL, 2000, NULL, '["prod_panel_mono_400w", "prod_panel_poly_320w", "prod_panel_bifacial_450w"]', NULL, 500, 23, 1, NOW() - INTERVAL '3 days', NOW() + INTERVAL '45 days', true, false, true, NOW(), NOW()),

('offer_free_shipping', 'FREESHIP', 'Free Shipping on Orders Over €500', 'Enjoy free shipping on all orders over €500. No weight limits!', 'free_shipping', 0, NULL, 500, NULL, NULL, NULL, NULL, 156, NULL, NOW() - INTERVAL '10 days', NOW() + INTERVAL '60 days', true, true, false, NOW(), NOW()),

('offer_battery_special', 'BATTERY20', 'Battery Storage Special', 'Save 20% on all battery storage systems. Limited time offer!', 'percentage', 20, 1000, 1000, NULL, '["prod_battery_10kwh"]', NULL, 100, 8, 1, NOW() - INTERVAL '5 days', NOW() + INTERVAL '20 days', true, false, true, NOW(), NOW()),

('offer_inverter_deal', 'INVERTER15', 'Inverter Deal - 15% Off', 'Special discount on all inverters. Upgrade your solar system today!', 'percentage', 15, 300, 500, NULL, '["prod_inv_string_5kw", "prod_inv_micro_300w"]', NULL, 200, 34, 2, NOW() - INTERVAL '2 days', NOW() + INTERVAL '25 days', true, false, false, NOW(), NOW());

-- Insert Blog Posts
INSERT INTO blog_posts (id, title, slug, excerpt, content, author_id, category, tags, featured_image, is_published, is_featured, views_count, reading_time, seo_title, seo_description, published_at, created_at, updated_at) VALUES

('blog_solar_guide_2024', 'Complete Solar Installation Guide 2024', 'complete-solar-installation-guide-2024', 'Everything you need to know about installing solar panels in 2024, from planning to maintenance.', 'Solar energy has become increasingly popular as homeowners seek sustainable and cost-effective energy solutions. This comprehensive guide covers everything you need to know about solar installation in 2024...', 'admin', 'Installation Guide', '["solar panels", "installation", "guide", "2024", "renewable energy"]', 'https://images.unsplash.com/photo-1509391366360-2e959784a276?w=1200&h=600&fit=crop', true, true, 1247, 8, 'Complete Solar Installation Guide 2024 | SolarShop', 'Learn everything about solar panel installation in 2024. Complete guide covering planning, installation, and maintenance.', NOW() - INTERVAL '5 days', NOW() - INTERVAL '5 days', NOW()),

('blog_battery_storage_benefits', 'Why Battery Storage is Essential for Solar Systems', 'why-battery-storage-essential-solar-systems', 'Discover the key benefits of adding battery storage to your solar system and how it maximizes your investment.', 'Battery storage systems have revolutionized the solar industry by providing homeowners with energy independence and backup power capabilities...', 'admin', 'Energy Storage', '["battery storage", "solar batteries", "energy independence", "backup power"]', 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200&h=600&fit=crop', true, true, 892, 6, 'Why Battery Storage is Essential for Solar Systems | SolarShop', 'Discover the benefits of solar battery storage systems and how they provide energy independence and backup power.', NOW() - INTERVAL '10 days', NOW() - INTERVAL '10 days', NOW()),

('blog_solar_maintenance_tips', '10 Essential Solar Panel Maintenance Tips', 'essential-solar-panel-maintenance-tips', 'Keep your solar panels performing at their best with these essential maintenance tips and best practices.', 'Proper maintenance is crucial for ensuring your solar panels continue to operate efficiently and last for decades...', 'admin', 'Maintenance', '["solar maintenance", "panel cleaning", "performance optimization", "tips"]', 'https://images.unsplash.com/photo-1497435334941-8c899ee9e8e9?w=1200&h=600&fit=crop', true, false, 634, 5, '10 Essential Solar Panel Maintenance Tips | SolarShop', 'Learn essential solar panel maintenance tips to keep your system performing optimally for years to come.', NOW() - INTERVAL '15 days', NOW() - INTERVAL '15 days', NOW()),

('blog_inverter_comparison', 'String vs Micro Inverters: Which is Right for You?', 'string-vs-micro-inverters-comparison', 'Compare string inverters and micro inverters to determine the best choice for your solar installation.', 'Choosing the right inverter is crucial for your solar system performance. This detailed comparison helps you understand the differences...', 'admin', 'Technology', '["inverters", "string inverters", "micro inverters", "comparison", "solar technology"]', 'https://images.unsplash.com/photo-1497435334941-8c899ee9e8e9?w=1200&h=600&fit=crop', true, false, 756, 7, 'String vs Micro Inverters Comparison | SolarShop', 'Compare string and micro inverters to choose the best option for your solar system installation.', NOW() - INTERVAL '8 days', NOW() - INTERVAL '8 days', NOW()),

('blog_solar_roi_2024', 'Solar Panel ROI: What to Expect in 2024', 'solar-panel-roi-what-to-expect-2024', 'Understand the return on investment for solar panels in 2024, including payback periods and long-term savings.', 'Investing in solar panels is not just about environmental benefits – it is also a smart financial decision...', 'admin', 'Financial', '["solar ROI", "return on investment", "solar savings", "payback period", "2024"]', 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=1200&h=600&fit=crop', true, true, 1123, 9, 'Solar Panel ROI: What to Expect in 2024 | SolarShop', 'Learn about solar panel return on investment, payback periods, and long-term savings in 2024.', NOW() - INTERVAL '3 days', NOW() - INTERVAL '3 days', NOW());

-- Note: User profiles will be created automatically via triggers when users register
-- Cart items will be created dynamically when users add items to cart

-- Update sequences to ensure proper ID generation
SELECT setval('categories_id_seq', (SELECT MAX(id::int) FROM categories WHERE id ~ '^[0-9]+$'), true);
SELECT setval('products_id_seq', (SELECT MAX(id::int) FROM products WHERE id ~ '^[0-9]+$'), true);
SELECT setval('offers_id_seq', (SELECT MAX(id::int) FROM offers WHERE id ~ '^[0-9]+$'), true);
SELECT setval('blog_posts_id_seq', (SELECT MAX(id::int) FROM blog_posts WHERE id ~ '^[0-9]+$'), true);

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS idx_products_category_featured ON products(category_id, is_featured);
CREATE INDEX IF NOT EXISTS idx_products_price_range ON products(price) WHERE is_active = true;
CREATE INDEX IF NOT EXISTS idx_products_stock_status ON products(stock_status, in_stock);
CREATE INDEX IF NOT EXISTS idx_offers_active_dates ON offers(is_active, start_date, end_date);
CREATE INDEX IF NOT EXISTS idx_blog_posts_published ON blog_posts(is_published, published_at);
CREATE INDEX IF NOT EXISTS idx_blog_posts_featured ON blog_posts(is_featured, published_at);

-- Insert some sample reviews/ratings (these would normally come from user interactions)
COMMENT ON TABLE products IS 'Sample ratings and reviews are simulated in the seed data. In production, these would come from actual user reviews.';

COMMIT; 